name: WidgetGo2Trip

on:
  push:
    branches: 
      - 'main'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses : actions/checkout@v1

      - name: Remove package-lock
        run : rm package-lock.json
      
      - name: Install node/modules
        run : npm install
      
      - name: Build the project
        run : npm run build
        
      - name: List files
        run : ls -la
        
      - name: Retrive build files app.js
        run : cp dist/js/app.js .
      
      - name: Retrive build files app.css
        run : cp dist/css/app.css .
      
      - name: List files
        run : ls -la
        
      - name: Send all materials to real server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_OF_REAL_SERVER }}
          username: ${{ secrets.USER_OF_REAL_SERVER }}
          password: ${{ secrets.PASSWORD_OF_REAL_SERVER }}
          port: "22"
          source: "app.js,app.css"
          target: "/var/www"
      
      - name: Send all materials to test server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_OF_TEST_SERVER }}
          username: ${{ secrets.USER_OF_TEST_SERVER }}
          password: ${{ secrets.PASSWORD_OF_TEST_SERVER }}
          port: "22"
          source: "app.js,app.css"
          target: "/var/www"
